# Generated by Django 4.0.3 on 2022-05-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Clients',
        ),
    ]
