# Generated by Django 4.0.3 on 2022-05-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_contact', '0003_okpage_alter_clients_options_alter_clients_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OkPage',
        ),
    ]
