# Generated by Django 4.0.3 on 2022-06-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('block_for_slider', 'block_for_slider'), ('block_for_slider1', 'block_for_slider1'), ('block_for_slider2', 'block_for_slider2'), ('block_for_slider3', 'block_for_slider3'), ('block_for_slider4', 'block_for_slider4'), ('block_for_main_post', 'block_for_main_post'), ('block_for_other_post', 'block_for_other_post'), ('block_for_other_post1', 'block_for_other_post1'), ('block_for_other_post2', 'block_for_other_post2'), ('block_for_other_post3', 'block_for_other_post3'), ('block_for_other_post4', 'block_for_other_post4'), ('block_for_tiled', 'block_for_tiled'), ('block_for_tiled1', 'block_for_tiled1'), ('block_for_tiled2', 'block_for_tiled2'), ('block_for_tiled3', 'block_for_tiled3'), ('block_for_special_item', 'block_for_special_item'), ('block_for_special_item1', 'block_for_special_item1'), ('block_for_special_item2', 'block_for_special_item2'), ('block_for_special_item3', 'block_for_special_item3'), ('block_for_special_item4', 'block_for_special_item4'), ('block_for_special_item5', 'block_for_special_item5'), ('block_for_special_item6', 'block_for_special_item6'), ('block_for_special_item7', 'block_for_special_item7'), ('block_for_special_item8', 'block_for_special_item8')], help_text='Название должно быть на латинице, будет использоваться\n                             в качестве переменной для Views', max_length=500, verbose_name='Название блока на главной страницы')),
                ('json_field', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Объект главной страницы',
                'verbose_name_plural': 'Отображение главной страницы',
                'ordering': ['-pk'],
            },
        ),
    ]
