# Generated by Django 4.0.3 on 2022-04-01 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=10, unique=True, verbose_name='url(ссылка)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subcategory',
            field=models.BooleanField(default=False, verbose_name='Подкатегория (для меню)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Название категории'),
        ),
    ]
