# Generated by Django 4.0.3 on 2022-04-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_on_home_page_alter_category_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='on_home_page',
        ),
        migrations.AddField(
            model_name='post',
            name='on_home_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
    ]
