# Generated by Django 4.0.3 on 2022-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_category_on_home_page_post_on_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=100, verbose_name='Верхний текст')),
                ('footer_text', models.CharField(max_length=100, verbose_name='Нижний текст')),
                ('carousel_img', models.ImageField(blank=True, help_text='Изображение должно быть 1560х680', upload_to='post_img/%Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.SlugField(default='#get_started', unique=True, verbose_name='url(ссылка)')),
            ],
        ),
        migrations.CreateModel(
            name='MainPagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('main_post_img', models.ImageField(blank=True, upload_to='post_img/%Y/%m/%d/', verbose_name='Изображение')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('on_home_page', models.BooleanField(default=False, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
