# Generated by Django 4.0.3 on 2022-04-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_carousel_mainpagepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Объект карусели', 'verbose_name_plural': 'Объекты карусели на главной странице'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='btn_text',
            field=models.CharField(default='Связаться с нами', max_length=25, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_img',
            field=models.ImageField(help_text='Изображение должно быть 1560х680', upload_to='post_img/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.SlugField(default='', unique=True, verbose_name='url(ссылка)'),
        ),
    ]
