# Generated by Django 4.0.3 on 2022-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_carousel_options_carousel_btn_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Пост на главной | Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Пост на главной | Контент')),
                ('main_post_img', models.ImageField(blank=True, upload_to='main_page/%Y/%m/%d/', verbose_name='Пост на главной | Изображение')),
                ('top_text_1', models.CharField(max_length=100, verbose_name='Слайд карусели 1 | Верхний текст')),
                ('footer_text_1', models.CharField(max_length=100, verbose_name='Слайд карусели 1 | Нижний текст')),
                ('carousel_img_1', models.ImageField(help_text='Изображение должно быть 1560х680', upload_to='main_page/%Y/%m/%d/', verbose_name='Слайд карусели 1 | Изображение')),
                ('url_1', models.SlugField(default='', unique=True, verbose_name='Слайд карусели 1 | url(ссылка)')),
                ('btn_text_1', models.CharField(default='Связаться с нами', max_length=25, verbose_name='Слайд карусели 1 | Текст на кнопке')),
                ('top_text_2', models.CharField(max_length=100, verbose_name='Слайд карусели 2 | Верхний текст')),
                ('footer_text_2', models.CharField(max_length=100, verbose_name='Слайд карусели 2 | Нижний текст')),
                ('carousel_img_2', models.ImageField(help_text='Изображение должно быть 1560х680', upload_to='main_page/%Y/%m/%d/', verbose_name='Слайд карусели 2 | Изображение')),
                ('url_2', models.SlugField(default='', unique=True, verbose_name='Слайд карусели 2 | url(ссылка)')),
                ('btn_text_2', models.CharField(default='Связаться с нами', max_length=25, verbose_name='Слайд карусели 2 | Текст на кнопке')),
                ('top_text_3', models.CharField(max_length=100, verbose_name='Слайд карусели 3 |Верхний текст')),
                ('footer_text_3', models.CharField(max_length=100, verbose_name='Слайд карусели 3 |Нижний текст')),
                ('carousel_img_3', models.ImageField(help_text='Изображение должно быть 1560х680', upload_to='main_page/%Y/%m/%d/', verbose_name='Слайд карусели 3 |Изображение')),
                ('url_3', models.SlugField(default='', unique=True, verbose_name='Слайд карусели 3 |url(ссылка)')),
                ('btn_text_3', models.CharField(default='Связаться с нами', max_length=25, verbose_name='Слайд карусели 3 |Текст на кнопке')),
                ('top_text_4', models.CharField(max_length=100, verbose_name='Слайд карусели 4 |Верхний текст')),
                ('footer_text_4', models.CharField(max_length=100, verbose_name='Слайд карусели 4 |Нижний текст')),
                ('carousel_img_4', models.ImageField(help_text='Изображение должно быть 1560х680', upload_to='main_page/%Y/%m/%d/', verbose_name='Слайд карусели 4 |Изображение')),
                ('url_4', models.SlugField(default='', unique=True, verbose_name='Слайд карусели 4 |url(ссылка)')),
                ('btn_text_4', models.CharField(default='Связаться с нами', max_length=25, verbose_name='Слайд карусели 4 |Текст на кнопке')),
                ('photo_stats', models.ImageField(help_text='Изображение должно быть 266х300', upload_to='main_page/%Y/%m/%d/', verbose_name='Статы | Фото')),
                ('text_stats1', models.CharField(help_text='Текст должен быть в формате: "Текст%цифра" Без кавычек. \n                                   Например: "Успешно сданные отчетности%100"', max_length=50, verbose_name='Статы | Текс над полосой загрузки 1')),
                ('text_stats2', models.CharField(help_text='Текст должен быть в формате: "Текст%цифра" Без кавычек. \n                                   Например: "Успешно сданные отчетности%100"', max_length=50, verbose_name='Статы | Текс над полосой загрузки 2')),
                ('text_stats3', models.CharField(help_text='Текст должен быть в формате: "Текст%цифра" Без кавычек. \n                                   Например: "Успешно сданные отчетности%100"', max_length=50, verbose_name='Статы | Текс над полосой загрузки 3')),
                ('text_stats4', models.CharField(help_text='Текст должен быть в формате: "Текст%цифра" Без кавычек. \n                                   Например: "Успешно сданные отчетности%100"', max_length=50, verbose_name='Статы | Текс над полосой загрузки 4')),
                ('exp_item1', models.CharField(help_text='Текст должен быть в формате: "цифра%текст" Без кавычек. \n                                 Например: "10%лет опыта работы!"', max_length=50, verbose_name='Опыт работы | Цифра и текст, отображаемый под цифрой 1')),
                ('exp_item2', models.CharField(help_text='Текст должен быть в формате: "цифра%текст" Без кавычек. \n                                 Например: "10%лет опыта работы!"', max_length=50, verbose_name='Опыт работы | Цифра и текст, отображаемый под цифрой 2')),
                ('exp_item3', models.CharField(help_text='Текст должен быть в формате: "цифра%текст" Без кавычек. \n                                 Например: "10%лет опыта работы!"', max_length=50, verbose_name='Опыт работы | Цифра и текст, отображаемый под цифрой 3')),
                ('tiled_title', models.CharField(default='Плиточное меню | Заголовок плиточного меню', max_length=50)),
                ('tiled_intro1', models.CharField(max_length=500, verbose_name='Плиточное меню | Левый текст над плиточным меню')),
                ('tiled_intro2', models.CharField(max_length=500, verbose_name='Плиточное меню | Правый текст над плиточным меню')),
                ('tiled_item_title1', models.CharField(help_text='Текст должен быть в несколько коротких предложений, \n                                         разделенный точками, они будут служить сигналом к переносу строки. \n                                         Например: "Некая документация для ООО. Ещё одна документация для ООО"', max_length=400, verbose_name='Плиточное меню | Текст на левой плитке')),
                ('tiled_item_title2', models.CharField(help_text='Текст должен быть в несколько коротких предложений, \n                                         разделенный точками, они будут служить сигналом к переносу строки. \n                                         Например: "Некая документация для ИП. Ещё одна документация для ИП"', max_length=400, verbose_name='Плиточное меню | Текст на правой плитке')),
            ],
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='MainPagePost',
        ),
    ]
