# Generated by Django 4.0.3 on 2022-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_mainpagemodel_btn_text_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagemodel',
            name='json_field',
            field=models.JSONField(default={'text': 'string', 'text1': 'string', 'url': 'string'}),
        ),
    ]
