# Generated by Django 4.0.3 on 2022-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_mainpagemodel_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagemodel',
            name='json_field',
            field=models.JSONField(blank=True, default={'text': 'string', 'text1': 'string', 'url': 'string'}),
        ),
    ]
