# Generated by Django 4.0.3 on 2022-05-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_mainpagemodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='on_home_page',
        ),
    ]
